#ifndef SMART_CITY_SOCKET_SERVER_PROTOCOL_H
#define SMART_CITY_SOCKET_SERVER_PROTOCOL_H

enum eddi_smartcity_protocol {
    VEHICLE = 1,
    ELECTRIC_PLANT,
    SHOOTING_RANGE,
    GAS_SENSOR,
    TRAFFIC_CONTROL,
    CENTRAL_SOCKET_SERVER,
    CRIME_PREVENTION_CCTV,
    TRAFFIC_MONITOR_CCTV,
    EDGE_DEVICE,
    CENTRAL_WEB_SERVER,
    END
};

#define CALL_BUFFER_COUNT           (END)
#define CALL_BUFFER                 ((END) - (1))

#endif //SMART_CITY_SOCKET_SERVER_PROTOCOL_H
