#ifndef SMART_CITY_SOCKET_SERVER_PROTOCOL_H
#define SMART_CITY_SOCKET_SERVER_PROTOCOL_H

enum eddi_smartcity_protocol {
    VEHICLE = 1,
    ELECTRIC_PLANT_GAS_SENSOR = 2,
    ELECTRIC_PLANT_BILLBOARD_DISPLAY = 3,
    ELECTRIC_PLANT_VEHICLE_CHARGER = 4,
    ELECTRIC_PLANT_TRAFFIC_MONITOR = 5,
    ELECTRIC_PLANT_TRAFFIC_CONTROL = 6,
    ELECTRIC_PLANT_OUTPUT_LINE = 7,
    ELECTRIC_PLANT_BATTERY_CELL = 8,
    SHOOTING_RANGE = 9,
    GAS_SENSOR = 10,
    TRAFFIC_CONTROL_LIFT = 11,
    TRAFFIC_CONTROL_TRAFFIC_LIGHT = 12,
    TRAFFIC_CONTROL_BARRICADE = 13,
    TRAFFIC_CONTROL_STREET_LAMP = 14,
    CENTRAL_SOCKET_SERVER = 15,
    CRIME_PREVENTION_CCTV = 16,
    TRAFFIC_MONITOR_CCTV = 17,
    EDGE_DEVICE = 18,
    CENTRAL_WEB_SERVER = 19,
    END
};

#define CALL_BUFFER_COUNT           (END)
#define CALL_BUFFER                 ((END) - (1))

#endif //SMART_CITY_SOCKET_SERVER_PROTOCOL_H
