#ifndef SMART_CITY_SOCKET_SERVER_ELECTRIC_PLANT_COMMAND_H
#define SMART_CITY_SOCKET_SERVER_ELECTRIC_PLANT_COMMAND_H

enum eddi_smartcity_electric_plant_protocol {
    ELECTRIC_PLANT_ID_ISSUANCE = 1,
    ELECTRIC_PLANT_EDGE_POWER_CONTROL = 2,
    ELECTRIC_PLANT_EACH_OUTPUT_CURRENT_STATUS = 3,
    ELECTRIC_PLANT_BATTERY_EACH_CELL_VOLTAGE_STATUS = 4,
    ELECTRIC_PLANT_BATTERY_MODULE_TEMPERATURE_STATUS = 5,
    ELECTRIC_PLANT_BATTERY_HEALTH_STATUS = 6,
    ELECTRIC_PLANT_BATTERY_CHARGE = 7,
    ELECTRIC_PLANT_END
};

#define EP_CALL_BUFFER_COUNT          (ELECTRIC_PLANT_END)
#define EP_CALL_BUFFER                ((ELECTRIC_PLANT_END) - (1))

#endif //SMART_CITY_SOCKET_SERVER_ELECTRIC_PLANT_COMMAND_H
