#ifndef SMART_CITY_SOCKET_SERVER_ELECTRIC_PLANT_COMMAND_HANDLER_H
#define SMART_CITY_SOCKET_SERVER_ELECTRIC_PLANT_COMMAND_HANDLER_H

void electric_plant_dummy (void *);
void electric_plant_id_issuance (void *);

#endif //SMART_CITY_SOCKET_SERVER_ELECTRIC_PLANT_COMMAND_HANDLER_H
