#ifndef SMART_CITY_SOCKET_SERVER_ELECTRIC_PLANT_COMMAND_HANDLER_H
#define SMART_CITY_SOCKET_SERVER_ELECTRIC_PLANT_COMMAND_HANDLER_H

void ep_dummy (void *);
void ep_id_issuance (void *);

#endif //SMART_CITY_SOCKET_SERVER_ELECTRIC_PLANT_COMMAND_HANDLER_H
