// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module system_v_gamma_lut_0_1_Gamma (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        imgRgb_dout,
        imgRgb_empty_n,
        imgRgb_read,
        imgGamma_din,
        imgGamma_full_n,
        imgGamma_write,
        width,
        height,
        gamma_lut_0_address0,
        gamma_lut_0_ce0,
        gamma_lut_0_q0,
        gamma_lut_1_address0,
        gamma_lut_1_ce0,
        gamma_lut_1_q0,
        gamma_lut_2_address0,
        gamma_lut_2_ce0,
        gamma_lut_2_q0
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [47:0] imgRgb_dout;
input   imgRgb_empty_n;
output   imgRgb_read;
output  [47:0] imgGamma_din;
input   imgGamma_full_n;
output   imgGamma_write;
input  [15:0] width;
input  [15:0] height;
output  [9:0] gamma_lut_0_address0;
output   gamma_lut_0_ce0;
input  [15:0] gamma_lut_0_q0;
output  [9:0] gamma_lut_1_address0;
output   gamma_lut_1_ce0;
input  [15:0] gamma_lut_1_q0;
output  [9:0] gamma_lut_2_address0;
output   gamma_lut_2_ce0;
input  [15:0] gamma_lut_2_q0;

reg ap_done;
reg ap_idle;
reg start_write;
reg imgRgb_read;
reg imgGamma_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
wire    ap_CS_fsm_state2;
wire   [10:0] empty_65_fu_121_p1;
reg   [9:0] lut_0_V_0_address0;
reg    lut_0_V_0_ce0;
reg    lut_0_V_0_we0;
wire   [9:0] lut_0_V_0_q0;
reg   [9:0] lut_1_V_0_address0;
reg    lut_1_V_0_ce0;
reg    lut_1_V_0_we0;
wire   [9:0] lut_1_V_0_q0;
reg   [9:0] lut_2_V_0_address0;
reg    lut_2_V_0_ce0;
reg    lut_2_V_0_we0;
wire   [9:0] lut_2_V_0_q0;
wire    grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_ap_start;
wire    grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_ap_done;
wire    grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_ap_idle;
wire    grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_ap_ready;
wire   [9:0] grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_gamma_lut_0_address0;
wire    grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_gamma_lut_0_ce0;
wire   [9:0] grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_gamma_lut_1_address0;
wire    grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_gamma_lut_1_ce0;
wire   [9:0] grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_gamma_lut_2_address0;
wire    grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_gamma_lut_2_ce0;
wire   [9:0] grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_0_V_0_address0;
wire    grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_0_V_0_ce0;
wire    grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_0_V_0_we0;
wire   [9:0] grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_0_V_0_d0;
wire   [9:0] grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_1_V_0_address0;
wire    grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_1_V_0_ce0;
wire    grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_1_V_0_we0;
wire   [9:0] grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_1_V_0_d0;
wire   [9:0] grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_2_V_0_address0;
wire    grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_2_V_0_ce0;
wire    grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_2_V_0_we0;
wire   [9:0] grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_2_V_0_d0;
wire    grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_ap_start;
wire    grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_ap_done;
wire    grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_ap_idle;
wire    grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_ap_ready;
wire    grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_imgRgb_read;
wire   [47:0] grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_imgGamma_din;
wire    grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_imgGamma_write;
wire   [10:0] grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_width_load_cast;
wire   [9:0] grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_lut_1_V_0_address0;
wire    grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_lut_1_V_0_ce0;
wire   [9:0] grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_lut_2_V_0_address0;
wire    grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_lut_2_V_0_ce0;
wire   [9:0] grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_lut_0_V_0_address0;
wire    grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_lut_0_V_0_ce0;
reg    grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_ap_start_reg;
reg    ap_block_state1_ignore_call16;
reg    grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_ap_start_reg;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln283_fu_128_p2;
wire    ap_CS_fsm_state4;
reg   [10:0] y_fu_56;
wire   [10:0] y_2_fu_133_p2;
reg    ap_block_state1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_ap_start_reg = 1'b0;
#0 grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_ap_start_reg = 1'b0;
end

system_v_gamma_lut_0_1_Gamma_lut_0_V_0 #(
    .DataWidth( 10 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
lut_0_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lut_0_V_0_address0),
    .ce0(lut_0_V_0_ce0),
    .we0(lut_0_V_0_we0),
    .d0(grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_0_V_0_d0),
    .q0(lut_0_V_0_q0)
);

system_v_gamma_lut_0_1_Gamma_lut_0_V_0 #(
    .DataWidth( 10 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
lut_1_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lut_1_V_0_address0),
    .ce0(lut_1_V_0_ce0),
    .we0(lut_1_V_0_we0),
    .d0(grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_1_V_0_d0),
    .q0(lut_1_V_0_q0)
);

system_v_gamma_lut_0_1_Gamma_lut_0_V_0 #(
    .DataWidth( 10 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
lut_2_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lut_2_V_0_address0),
    .ce0(lut_2_V_0_ce0),
    .we0(lut_2_V_0_we0),
    .d0(grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_2_V_0_d0),
    .q0(lut_2_V_0_q0)
);

system_v_gamma_lut_0_1_Gamma_Pipeline_VITIS_LOOP_273_1 grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_ap_start),
    .ap_done(grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_ap_done),
    .ap_idle(grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_ap_idle),
    .ap_ready(grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_ap_ready),
    .gamma_lut_0_address0(grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_gamma_lut_0_address0),
    .gamma_lut_0_ce0(grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_gamma_lut_0_ce0),
    .gamma_lut_0_q0(gamma_lut_0_q0),
    .gamma_lut_1_address0(grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_gamma_lut_1_address0),
    .gamma_lut_1_ce0(grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_gamma_lut_1_ce0),
    .gamma_lut_1_q0(gamma_lut_1_q0),
    .gamma_lut_2_address0(grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_gamma_lut_2_address0),
    .gamma_lut_2_ce0(grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_gamma_lut_2_ce0),
    .gamma_lut_2_q0(gamma_lut_2_q0),
    .lut_0_V_0_address0(grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_0_V_0_address0),
    .lut_0_V_0_ce0(grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_0_V_0_ce0),
    .lut_0_V_0_we0(grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_0_V_0_we0),
    .lut_0_V_0_d0(grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_0_V_0_d0),
    .lut_1_V_0_address0(grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_1_V_0_address0),
    .lut_1_V_0_ce0(grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_1_V_0_ce0),
    .lut_1_V_0_we0(grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_1_V_0_we0),
    .lut_1_V_0_d0(grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_1_V_0_d0),
    .lut_2_V_0_address0(grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_2_V_0_address0),
    .lut_2_V_0_ce0(grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_2_V_0_ce0),
    .lut_2_V_0_we0(grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_2_V_0_we0),
    .lut_2_V_0_d0(grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_2_V_0_d0)
);

system_v_gamma_lut_0_1_Gamma_Pipeline_VITIS_LOOP_285_4 grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_ap_start),
    .ap_done(grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_ap_done),
    .ap_idle(grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_ap_idle),
    .ap_ready(grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_ap_ready),
    .imgRgb_dout(imgRgb_dout),
    .imgRgb_empty_n(imgRgb_empty_n),
    .imgRgb_read(grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_imgRgb_read),
    .imgGamma_din(grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_imgGamma_din),
    .imgGamma_full_n(imgGamma_full_n),
    .imgGamma_write(grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_imgGamma_write),
    .width_load_cast(grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_width_load_cast),
    .lut_1_V_0_address0(grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_lut_1_V_0_address0),
    .lut_1_V_0_ce0(grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_lut_1_V_0_ce0),
    .lut_1_V_0_q0(lut_1_V_0_q0),
    .lut_2_V_0_address0(grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_lut_2_V_0_address0),
    .lut_2_V_0_ce0(grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_lut_2_V_0_ce0),
    .lut_2_V_0_q0(lut_2_V_0_q0),
    .lut_0_V_0_address0(grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_lut_0_V_0_address0),
    .lut_0_V_0_ce0(grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_lut_0_V_0_ce0),
    .lut_0_V_0_q0(lut_0_V_0_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln283_fu_128_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_ap_start_reg <= 1'b0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_ap_start_reg <= 1'b1;
        end else if ((grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_ap_ready == 1'b1)) begin
            grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln283_fu_128_p2 == 1'd0))) begin
            grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_ap_start_reg <= 1'b1;
        end else if ((grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_ap_ready == 1'b1)) begin
            grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_56 <= 11'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln283_fu_128_p2 == 1'd0))) begin
        y_fu_56 <= y_2_fu_133_p2;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln283_fu_128_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        imgGamma_write = grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_imgGamma_write;
    end else begin
        imgGamma_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        imgRgb_read = grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_imgRgb_read;
    end else begin
        imgRgb_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln283_fu_128_p2 == 1'd1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        lut_0_V_0_address0 = grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_lut_0_V_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        lut_0_V_0_address0 = grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_0_V_0_address0;
    end else begin
        lut_0_V_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        lut_0_V_0_ce0 = grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_lut_0_V_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        lut_0_V_0_ce0 = grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_0_V_0_ce0;
    end else begin
        lut_0_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        lut_0_V_0_we0 = grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_0_V_0_we0;
    end else begin
        lut_0_V_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        lut_1_V_0_address0 = grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_lut_1_V_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        lut_1_V_0_address0 = grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_1_V_0_address0;
    end else begin
        lut_1_V_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        lut_1_V_0_ce0 = grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_lut_1_V_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        lut_1_V_0_ce0 = grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_1_V_0_ce0;
    end else begin
        lut_1_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        lut_1_V_0_we0 = grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_1_V_0_we0;
    end else begin
        lut_1_V_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        lut_2_V_0_address0 = grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_lut_2_V_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        lut_2_V_0_address0 = grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_2_V_0_address0;
    end else begin
        lut_2_V_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        lut_2_V_0_ce0 = grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_lut_2_V_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        lut_2_V_0_ce0 = grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_2_V_0_ce0;
    end else begin
        lut_2_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        lut_2_V_0_we0 = grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_lut_2_V_0_we0;
    end else begin
        lut_2_V_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln283_fu_128_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call16 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign empty_65_fu_121_p1 = height[10:0];

assign gamma_lut_0_address0 = grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_gamma_lut_0_address0;

assign gamma_lut_0_ce0 = grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_gamma_lut_0_ce0;

assign gamma_lut_1_address0 = grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_gamma_lut_1_address0;

assign gamma_lut_1_ce0 = grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_gamma_lut_1_ce0;

assign gamma_lut_2_address0 = grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_gamma_lut_2_address0;

assign gamma_lut_2_ce0 = grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_gamma_lut_2_ce0;

assign grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_ap_start = grp_Gamma_Pipeline_VITIS_LOOP_273_1_fu_84_ap_start_reg;

assign grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_ap_start = grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_ap_start_reg;

assign grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_width_load_cast = width[10:0];

assign icmp_ln283_fu_128_p2 = ((y_fu_56 == empty_65_fu_121_p1) ? 1'b1 : 1'b0);

assign imgGamma_din = grp_Gamma_Pipeline_VITIS_LOOP_285_4_fu_100_imgGamma_din;

assign start_out = real_start;

assign y_2_fu_133_p2 = (y_fu_56 + 11'd1);

endmodule //system_v_gamma_lut_0_1_Gamma
