#ifndef SMART_CITY_SOCKET_SERVER_GS_COMMAND_HANDLER_H
#define SMART_CITY_SOCKET_SERVER_GS_COMMAND_HANDLER_H

void gs_dummy (void *);
void gs_id_issuance (void *);

#endif //SMART_CITY_SOCKET_SERVER_GS_COMMAND_HANDLER_H
