// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module system_v_demosaic_0_1_DebayerRatBorBatR (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        imgG_dout,
        imgG_empty_n,
        imgG_read,
        imgRB_din,
        imgRB_full_n,
        imgRB_write,
        height,
        width,
        bayerPhase_c9_dout,
        bayerPhase_c9_empty_n,
        bayerPhase_c9_read,
        bayerPhase_c_din,
        bayerPhase_c_full_n,
        bayerPhase_c_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [47:0] imgG_dout;
input   imgG_empty_n;
output   imgG_read;
output  [47:0] imgRB_din;
input   imgRB_full_n;
output   imgRB_write;
input  [10:0] height;
input  [10:0] width;
input  [15:0] bayerPhase_c9_dout;
input   bayerPhase_c9_empty_n;
output   bayerPhase_c9_read;
output  [15:0] bayerPhase_c_din;
input   bayerPhase_c_full_n;
output   bayerPhase_c_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg imgG_read;
reg imgRB_write;
reg bayerPhase_c9_read;
reg bayerPhase_c_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    bayerPhase_c9_blk_n;
reg    bayerPhase_c_blk_n;
wire   [10:0] loopHeight_fu_370_p2;
wire   [0:0] x_phase_fu_376_p1;
reg   [0:0] x_phase_reg_1086;
reg   [14:0] trunc_ln574_1_i_reg_1091;
wire   [11:0] out_y_i_fu_519_p2;
reg   [11:0] out_y_i_reg_1177;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln582_fu_408_p2;
wire   [14:0] xor_i_fu_536_p2;
reg   [14:0] xor_i_reg_1182;
wire   [0:0] red_i_fu_542_p2;
reg   [0:0] red_i_reg_1187;
wire   [1:0] idxprom238_t_i_fu_548_p3;
reg   [1:0] idxprom238_t_i_reg_1192;
wire   [1:0] idxprom373_t_i_fu_557_p3;
reg   [1:0] idxprom373_t_i_reg_1197;
wire   [0:0] cmp37_i_fu_566_p2;
reg   [0:0] cmp37_i_reg_1202;
wire   [0:0] cmp140_i_fu_572_p2;
reg   [0:0] cmp140_i_reg_1207;
wire   [29:0] lineBuffer_val_V_0_q1;
wire   [29:0] lineBuffer_val_V_1_q1;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_ap_start;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_ap_done;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_ap_idle;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_ap_ready;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_imgG_read;
wire   [47:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_imgRB_din;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_imgRB_write;
wire   [10:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_add_ln582_i;
wire   [10:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_0_i_address0;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_0_i_ce0;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_0_i_we0;
wire   [29:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_0_i_d0;
wire   [10:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_0_i_address1;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_0_i_ce1;
wire   [10:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_1_i_address0;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_1_i_ce0;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_1_i_we0;
wire   [29:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_1_i_d0;
wire   [10:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_1_i_address1;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_1_i_ce1;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_red_i;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_2_2_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_2_2_1_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_2_1_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_2_1_1_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_2_0_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_2_0_1_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_1_2_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_1_2_1_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_1_1_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_1_1_1_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_1_0_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_1_0_1_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_0_2_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_0_2_1_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_0_1_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_0_1_1_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_0_0_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_0_0_1_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_2_1_2_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_2_1_2_1_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_2_1_1_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_2_1_1_1_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_2_1_0_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_2_1_0_1_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_2_0_2_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_2_0_2_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_2_0_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_2_0_1_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_2_0_0_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_2_0_0_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_1_1_2_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_1_1_2_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_1_1_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_1_1_1_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_1_1_0_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_1_1_0_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_0_1_2_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_0_1_2_1_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_0_1_1_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_0_1_1_1_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_0_1_0_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_0_1_0_1_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_0_0_2_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_0_0_2_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_0_0_1_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_0_0_1_i_out_ap_vld;
wire   [9:0] grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_0_0_0_i_out;
wire    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_0_0_0_i_out_ap_vld;
reg    grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_ap_start_reg;
wire    ap_CS_fsm_state3;
reg   [10:0] y_fu_72;
wire   [10:0] y_4_fu_413_p2;
reg    ap_block_state1;
reg   [9:0] pixWindow_val_val_V_0_1_0_0_i_fu_76;
wire    ap_CS_fsm_state4;
reg   [9:0] pixWindow_val_val_V_0_1_1_0_i_fu_80;
reg   [9:0] pixWindow_val_val_V_0_1_2_0_i_fu_84;
reg   [9:0] pixWindow_val_val_V_0_2_0_0_i_fu_88;
reg   [9:0] pixWindow_val_val_V_0_2_1_0_i_fu_92;
reg   [9:0] pixWindow_val_val_V_0_2_2_0_i_fu_96;
reg   [9:0] pixWindow_val_val_V_1_2_0_0_i_fu_100;
reg   [9:0] pixWindow_val_val_V_1_2_1_0_i_fu_104;
reg   [9:0] pixWindow_val_val_V_1_2_2_0_i_fu_108;
reg   [9:0] pixWindow_val_val_V_2_1_0_0_i_fu_112;
reg   [9:0] pixWindow_val_val_V_2_1_1_0_i_fu_116;
reg   [9:0] pixWindow_val_val_V_2_1_2_0_i_fu_120;
reg   [9:0] pixWindow_val_val_V_2_2_0_0_i_fu_124;
reg   [9:0] pixWindow_val_val_V_2_2_1_0_i_fu_128;
reg   [9:0] pixWindow_val_val_V_2_2_2_0_i_fu_132;
reg   [9:0] pixBuf_val_V_0_0_0_i_fu_136;
reg   [9:0] pixBuf_val_V_0_1_0_i_fu_140;
reg   [9:0] pixBuf_val_V_0_2_0_i_fu_144;
reg   [9:0] pixBuf_val_V_1_0_0622_i_fu_148;
reg   [9:0] pixBuf_val_V_1_1_0623_i_fu_152;
reg   [9:0] pixBuf_val_V_1_2_0624_i_fu_156;
reg   [9:0] pixBuf_val_V_2_0_0625_i_fu_160;
reg   [9:0] pixBuf_val_V_2_1_0626_i_fu_164;
reg   [9:0] pixBuf_val_V_2_2_0627_i_fu_168;
wire   [11:0] zext_ln582_fu_404_p1;
wire   [0:0] empty_158_fu_515_p1;
wire   [0:0] out_y_cast_i_fu_526_p2;
wire   [14:0] and219_cast_i_fu_532_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_ap_start_reg = 1'b0;
end

system_v_demosaic_0_1_DebayerRatBorBatR_lineBuffer_val_V_0 #(
    .DataWidth( 30 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
lineBuffer_val_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_0_i_address0),
    .ce0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_0_i_ce0),
    .we0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_0_i_we0),
    .d0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_0_i_d0),
    .address1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_0_i_address1),
    .ce1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_0_i_ce1),
    .q1(lineBuffer_val_V_0_q1)
);

system_v_demosaic_0_1_DebayerRatBorBatR_lineBuffer_val_V_0 #(
    .DataWidth( 30 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
lineBuffer_val_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_1_i_address0),
    .ce0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_1_i_ce0),
    .we0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_1_i_we0),
    .d0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_1_i_d0),
    .address1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_1_i_address1),
    .ce1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_1_i_ce1),
    .q1(lineBuffer_val_V_1_q1)
);

system_v_demosaic_0_1_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2 grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_ap_start),
    .ap_done(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_ap_done),
    .ap_idle(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_ap_idle),
    .ap_ready(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_ap_ready),
    .imgG_dout(imgG_dout),
    .imgG_empty_n(imgG_empty_n),
    .imgG_read(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_imgG_read),
    .imgRB_din(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_imgRB_din),
    .imgRB_full_n(imgRB_full_n),
    .imgRB_write(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_imgRB_write),
    .pixBuf_val_V_2_2_0627_i(pixBuf_val_V_2_2_0627_i_fu_168),
    .pixBuf_val_V_2_1_0626_i(pixBuf_val_V_2_1_0626_i_fu_164),
    .pixBuf_val_V_2_0_0625_i(pixBuf_val_V_2_0_0625_i_fu_160),
    .pixBuf_val_V_1_2_0624_i(pixBuf_val_V_1_2_0624_i_fu_156),
    .pixBuf_val_V_1_1_0623_i(pixBuf_val_V_1_1_0623_i_fu_152),
    .pixBuf_val_V_1_0_0622_i(pixBuf_val_V_1_0_0622_i_fu_148),
    .pixBuf_val_V_0_2_0_i(pixBuf_val_V_0_2_0_i_fu_144),
    .pixBuf_val_V_0_1_0_i(pixBuf_val_V_0_1_0_i_fu_140),
    .pixBuf_val_V_0_0_0_i(pixBuf_val_V_0_0_0_i_fu_136),
    .pixWindow_val_val_V_2_2_2_0_i(pixWindow_val_val_V_2_2_2_0_i_fu_132),
    .pixWindow_val_val_V_2_2_1_0_i(pixWindow_val_val_V_2_2_1_0_i_fu_128),
    .pixWindow_val_val_V_2_2_0_0_i(pixWindow_val_val_V_2_2_0_0_i_fu_124),
    .pixWindow_val_val_V_2_1_2_0_i(pixWindow_val_val_V_2_1_2_0_i_fu_120),
    .pixWindow_val_val_V_2_1_1_0_i(pixWindow_val_val_V_2_1_1_0_i_fu_116),
    .pixWindow_val_val_V_2_1_0_0_i(pixWindow_val_val_V_2_1_0_0_i_fu_112),
    .pixWindow_val_val_V_1_2_2_0_i(pixWindow_val_val_V_1_2_2_0_i_fu_108),
    .pixWindow_val_val_V_1_2_1_0_i(pixWindow_val_val_V_1_2_1_0_i_fu_104),
    .pixWindow_val_val_V_1_2_0_0_i(pixWindow_val_val_V_1_2_0_0_i_fu_100),
    .pixWindow_val_val_V_0_2_2_0_i(pixWindow_val_val_V_0_2_2_0_i_fu_96),
    .pixWindow_val_val_V_0_2_1_0_i(pixWindow_val_val_V_0_2_1_0_i_fu_92),
    .pixWindow_val_val_V_0_2_0_0_i(pixWindow_val_val_V_0_2_0_0_i_fu_88),
    .pixWindow_val_val_V_0_1_2_0_i(pixWindow_val_val_V_0_1_2_0_i_fu_84),
    .pixWindow_val_val_V_0_1_1_0_i(pixWindow_val_val_V_0_1_1_0_i_fu_80),
    .pixWindow_val_val_V_0_1_0_0_i(pixWindow_val_val_V_0_1_0_0_i_fu_76),
    .add_ln582_i(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_add_ln582_i),
    .out_y_i(out_y_i_reg_1177),
    .x_phase_i(x_phase_reg_1086),
    .xor_i(xor_i_reg_1182),
    .width_cast(width),
    .lineBuffer_val_V_0_i_address0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_0_i_address0),
    .lineBuffer_val_V_0_i_ce0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_0_i_ce0),
    .lineBuffer_val_V_0_i_we0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_0_i_we0),
    .lineBuffer_val_V_0_i_d0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_0_i_d0),
    .lineBuffer_val_V_0_i_address1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_0_i_address1),
    .lineBuffer_val_V_0_i_ce1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_0_i_ce1),
    .lineBuffer_val_V_0_i_q1(lineBuffer_val_V_0_q1),
    .lineBuffer_val_V_1_i_address0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_1_i_address0),
    .lineBuffer_val_V_1_i_ce0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_1_i_ce0),
    .lineBuffer_val_V_1_i_we0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_1_i_we0),
    .lineBuffer_val_V_1_i_d0(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_1_i_d0),
    .lineBuffer_val_V_1_i_address1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_1_i_address1),
    .lineBuffer_val_V_1_i_ce1(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_lineBuffer_val_V_1_i_ce1),
    .lineBuffer_val_V_1_i_q1(lineBuffer_val_V_1_q1),
    .cmp37_i(cmp37_i_reg_1202),
    .cmp140_i(cmp140_i_reg_1207),
    .idxprom373_t_i(idxprom373_t_i_reg_1197),
    .red_i(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_red_i),
    .idxprom238_t_i(idxprom238_t_i_reg_1192),
    .pixBuf_val_V_2_2_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_2_2_1_i_out),
    .pixBuf_val_V_2_2_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_2_2_1_i_out_ap_vld),
    .pixBuf_val_V_2_1_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_2_1_1_i_out),
    .pixBuf_val_V_2_1_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_2_1_1_i_out_ap_vld),
    .pixBuf_val_V_2_0_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_2_0_1_i_out),
    .pixBuf_val_V_2_0_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_2_0_1_i_out_ap_vld),
    .pixBuf_val_V_1_2_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_1_2_1_i_out),
    .pixBuf_val_V_1_2_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_1_2_1_i_out_ap_vld),
    .pixBuf_val_V_1_1_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_1_1_1_i_out),
    .pixBuf_val_V_1_1_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_1_1_1_i_out_ap_vld),
    .pixBuf_val_V_1_0_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_1_0_1_i_out),
    .pixBuf_val_V_1_0_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_1_0_1_i_out_ap_vld),
    .pixBuf_val_V_0_2_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_0_2_1_i_out),
    .pixBuf_val_V_0_2_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_0_2_1_i_out_ap_vld),
    .pixBuf_val_V_0_1_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_0_1_1_i_out),
    .pixBuf_val_V_0_1_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_0_1_1_i_out_ap_vld),
    .pixBuf_val_V_0_0_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_0_0_1_i_out),
    .pixBuf_val_V_0_0_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_0_0_1_i_out_ap_vld),
    .pixWindow_val_val_V_2_1_2_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_2_1_2_1_i_out),
    .pixWindow_val_val_V_2_1_2_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_2_1_2_1_i_out_ap_vld),
    .pixWindow_val_val_V_2_1_1_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_2_1_1_1_i_out),
    .pixWindow_val_val_V_2_1_1_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_2_1_1_1_i_out_ap_vld),
    .pixWindow_val_val_V_2_1_0_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_2_1_0_1_i_out),
    .pixWindow_val_val_V_2_1_0_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_2_1_0_1_i_out_ap_vld),
    .pixWindow_val_val_V_2_0_2_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_2_0_2_i_out),
    .pixWindow_val_val_V_2_0_2_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_2_0_2_i_out_ap_vld),
    .pixWindow_val_val_V_2_0_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_2_0_1_i_out),
    .pixWindow_val_val_V_2_0_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_2_0_1_i_out_ap_vld),
    .pixWindow_val_val_V_2_0_0_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_2_0_0_i_out),
    .pixWindow_val_val_V_2_0_0_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_2_0_0_i_out_ap_vld),
    .pixWindow_val_val_V_1_1_2_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_1_1_2_i_out),
    .pixWindow_val_val_V_1_1_2_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_1_1_2_i_out_ap_vld),
    .pixWindow_val_val_V_1_1_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_1_1_1_i_out),
    .pixWindow_val_val_V_1_1_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_1_1_1_i_out_ap_vld),
    .pixWindow_val_val_V_1_1_0_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_1_1_0_i_out),
    .pixWindow_val_val_V_1_1_0_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_1_1_0_i_out_ap_vld),
    .pixWindow_val_val_V_0_1_2_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_0_1_2_1_i_out),
    .pixWindow_val_val_V_0_1_2_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_0_1_2_1_i_out_ap_vld),
    .pixWindow_val_val_V_0_1_1_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_0_1_1_1_i_out),
    .pixWindow_val_val_V_0_1_1_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_0_1_1_1_i_out_ap_vld),
    .pixWindow_val_val_V_0_1_0_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_0_1_0_1_i_out),
    .pixWindow_val_val_V_0_1_0_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_0_1_0_1_i_out_ap_vld),
    .pixWindow_val_val_V_0_0_2_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_0_0_2_i_out),
    .pixWindow_val_val_V_0_0_2_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_0_0_2_i_out_ap_vld),
    .pixWindow_val_val_V_0_0_1_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_0_0_1_i_out),
    .pixWindow_val_val_V_0_0_1_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_0_0_1_i_out_ap_vld),
    .pixWindow_val_val_V_0_0_0_i_out(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_0_0_0_i_out),
    .pixWindow_val_val_V_0_0_0_i_out_ap_vld(grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_0_0_0_i_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln582_fu_408_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln582_fu_408_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_ap_start_reg <= 1'b1;
        end else if ((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_ap_ready == 1'b1)) begin
            grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((bayerPhase_c_full_n == 1'b0) | (bayerPhase_c9_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_72 <= 11'd0;
    end else if (((icmp_ln582_fu_408_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        y_fu_72 <= y_4_fu_413_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln582_fu_408_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        cmp140_i_reg_1207 <= cmp140_i_fu_572_p2;
        cmp37_i_reg_1202 <= cmp37_i_fu_566_p2;
        idxprom238_t_i_reg_1192[1] <= idxprom238_t_i_fu_548_p3[1];
        idxprom373_t_i_reg_1197[1] <= idxprom373_t_i_fu_557_p3[1];
        out_y_i_reg_1177 <= out_y_i_fu_519_p2;
        red_i_reg_1187 <= red_i_fu_542_p2;
        xor_i_reg_1182 <= xor_i_fu_536_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        pixBuf_val_V_0_0_0_i_fu_136 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_0_0_1_i_out;
        pixBuf_val_V_0_1_0_i_fu_140 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_0_1_1_i_out;
        pixBuf_val_V_0_2_0_i_fu_144 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_0_2_1_i_out;
        pixBuf_val_V_1_0_0622_i_fu_148 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_1_0_1_i_out;
        pixBuf_val_V_1_1_0623_i_fu_152 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_1_1_1_i_out;
        pixBuf_val_V_1_2_0624_i_fu_156 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_1_2_1_i_out;
        pixBuf_val_V_2_0_0625_i_fu_160 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_2_0_1_i_out;
        pixBuf_val_V_2_1_0626_i_fu_164 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_2_1_1_i_out;
        pixBuf_val_V_2_2_0627_i_fu_168 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixBuf_val_V_2_2_1_i_out;
        pixWindow_val_val_V_0_1_0_0_i_fu_76 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_0_0_0_i_out;
        pixWindow_val_val_V_0_1_1_0_i_fu_80 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_0_0_1_i_out;
        pixWindow_val_val_V_0_1_2_0_i_fu_84 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_0_0_2_i_out;
        pixWindow_val_val_V_0_2_0_0_i_fu_88 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_0_1_0_1_i_out;
        pixWindow_val_val_V_0_2_1_0_i_fu_92 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_0_1_1_1_i_out;
        pixWindow_val_val_V_0_2_2_0_i_fu_96 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_0_1_2_1_i_out;
        pixWindow_val_val_V_1_2_0_0_i_fu_100 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_1_1_0_i_out;
        pixWindow_val_val_V_1_2_1_0_i_fu_104 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_1_1_1_i_out;
        pixWindow_val_val_V_1_2_2_0_i_fu_108 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_1_1_2_i_out;
        pixWindow_val_val_V_2_1_0_0_i_fu_112 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_2_0_0_i_out;
        pixWindow_val_val_V_2_1_1_0_i_fu_116 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_2_0_1_i_out;
        pixWindow_val_val_V_2_1_2_0_i_fu_120 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_2_0_2_i_out;
        pixWindow_val_val_V_2_2_0_0_i_fu_124 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_2_1_0_1_i_out;
        pixWindow_val_val_V_2_2_1_0_i_fu_128 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_2_1_1_1_i_out;
        pixWindow_val_val_V_2_2_2_0_i_fu_132 <= grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_pixWindow_val_val_V_2_1_2_1_i_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        trunc_ln574_1_i_reg_1091 <= {{bayerPhase_c9_dout[15:1]}};
        x_phase_reg_1086 <= x_phase_fu_376_p1;
    end
end

always @ (*) begin
    if (((bayerPhase_c_full_n == 1'b0) | (bayerPhase_c9_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln582_fu_408_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_c9_blk_n = bayerPhase_c9_empty_n;
    end else begin
        bayerPhase_c9_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((bayerPhase_c_full_n == 1'b0) | (bayerPhase_c9_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_c9_read = 1'b1;
    end else begin
        bayerPhase_c9_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_c_blk_n = bayerPhase_c_full_n;
    end else begin
        bayerPhase_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((bayerPhase_c_full_n == 1'b0) | (bayerPhase_c9_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_c_write = 1'b1;
    end else begin
        bayerPhase_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        imgG_read = grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_imgG_read;
    end else begin
        imgG_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        imgRB_write = grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_imgRB_write;
    end else begin
        imgRB_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln582_fu_408_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((bayerPhase_c_full_n == 1'b0) | (bayerPhase_c9_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln582_fu_408_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and219_cast_i_fu_532_p1 = out_y_cast_i_fu_526_p2;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((bayerPhase_c_full_n == 1'b0) | (bayerPhase_c9_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign bayerPhase_c_din = bayerPhase_c9_dout;

assign cmp140_i_fu_572_p2 = ((y_fu_72 != 11'd0) ? 1'b1 : 1'b0);

assign cmp37_i_fu_566_p2 = ((y_fu_72 < height) ? 1'b1 : 1'b0);

assign empty_158_fu_515_p1 = y_fu_72[0:0];

assign grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_add_ln582_i = (width + 11'd1);

assign grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_ap_start = grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_ap_start_reg;

assign grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_red_i = red_i_reg_1187;

assign icmp_ln582_fu_408_p2 = ((y_fu_72 == loopHeight_fu_370_p2) ? 1'b1 : 1'b0);

assign idxprom238_t_i_fu_548_p3 = ((red_i_fu_542_p2[0:0] == 1'b1) ? 2'd0 : 2'd2);

assign idxprom373_t_i_fu_557_p3 = ((red_i_fu_542_p2[0:0] == 1'b1) ? 2'd2 : 2'd0);

assign imgRB_din = grp_DebayerRatBorBatR_Pipeline_VITIS_LOOP_585_2_fu_302_imgRB_din;

assign loopHeight_fu_370_p2 = (height + 11'd1);

assign out_y_cast_i_fu_526_p2 = (empty_158_fu_515_p1 ^ 1'd1);

assign out_y_i_fu_519_p2 = ($signed(zext_ln582_fu_404_p1) + $signed(12'd4095));

assign red_i_fu_542_p2 = ((and219_cast_i_fu_532_p1 == trunc_ln574_1_i_reg_1091) ? 1'b1 : 1'b0);

assign start_out = real_start;

assign x_phase_fu_376_p1 = bayerPhase_c9_dout[0:0];

assign xor_i_fu_536_p2 = (trunc_ln574_1_i_reg_1091 ^ and219_cast_i_fu_532_p1);

assign y_4_fu_413_p2 = (y_fu_72 + 11'd1);

assign zext_ln582_fu_404_p1 = y_fu_72;

always @ (posedge ap_clk) begin
    idxprom238_t_i_reg_1192[0] <= 1'b0;
    idxprom373_t_i_reg_1197[0] <= 1'b0;
end

endmodule //system_v_demosaic_0_1_DebayerRatBorBatR
