// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module system_v_demosaic_0_1_DebayerRandBatG (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        imgRB_dout,
        imgRB_empty_n,
        imgRB_read,
        imgRgb_din,
        imgRgb_full_n,
        imgRgb_write,
        height,
        width,
        bayerPhase_c_dout,
        bayerPhase_c_empty_n,
        bayerPhase_c_read
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [47:0] imgRB_dout;
input   imgRB_empty_n;
output   imgRB_read;
output  [47:0] imgRgb_din;
input   imgRgb_full_n;
output   imgRgb_write;
input  [10:0] height;
input  [10:0] width;
input  [15:0] bayerPhase_c_dout;
input   bayerPhase_c_empty_n;
output   bayerPhase_c_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg imgRB_read;
reg imgRgb_write;
reg bayerPhase_c_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    bayerPhase_c_blk_n;
wire   [10:0] loopHeight_fu_321_p2;
wire   [0:0] x_phase_fu_327_p1;
reg   [0:0] x_phase_reg_941;
reg   [14:0] trunc_ln822_1_i_reg_946;
wire   [11:0] out_y_i_fu_458_p2;
reg   [11:0] out_y_i_reg_1022;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln830_fu_359_p2;
wire   [14:0] xor_i_fu_475_p2;
reg   [14:0] xor_i_reg_1027;
wire   [0:0] cmp37_i_fu_481_p2;
reg   [0:0] cmp37_i_reg_1032;
wire   [0:0] cmp140_i_fu_487_p2;
reg   [0:0] cmp140_i_reg_1037;
wire   [29:0] lineBuffer_val_V_0_q1;
wire   [29:0] lineBuffer_val_V_1_q1;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_ap_start;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_ap_done;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_ap_idle;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_ap_ready;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_imgRB_read;
wire   [47:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_imgRgb_din;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_imgRgb_write;
wire   [10:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_add_ln830_i;
wire   [10:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_0_i_address0;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_0_i_ce0;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_0_i_we0;
wire   [29:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_0_i_d0;
wire   [10:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_0_i_address1;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_0_i_ce1;
wire   [10:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_1_i_address0;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_1_i_ce0;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_1_i_we0;
wire   [29:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_1_i_d0;
wire   [10:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_1_i_address1;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_1_i_ce1;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_2_2_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_2_2_1_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_2_1_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_2_1_1_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_2_0_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_2_0_1_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_1_2_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_1_2_1_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_1_1_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_1_1_1_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_1_0_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_1_0_1_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_0_2_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_0_2_1_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_0_1_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_0_1_1_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_0_0_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_0_0_1_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_2_1_2_2_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_2_1_2_2_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_2_1_1_2_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_2_1_1_2_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_2_1_0_2_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_2_1_0_2_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_1_1_2_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_1_1_2_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_1_1_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_1_1_1_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_1_1_0_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_1_1_0_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_1_0_2_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_1_0_2_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_1_0_1_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_1_0_1_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_1_0_0_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_1_0_0_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_0_1_2_2_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_0_1_2_2_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_0_1_1_2_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_0_1_1_2_i_out_ap_vld;
wire   [9:0] grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_0_1_0_2_i_out;
wire    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_0_1_0_2_i_out_ap_vld;
reg    grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_ap_start_reg;
wire    ap_CS_fsm_state3;
reg   [10:0] y_fu_64;
wire   [10:0] y_6_fu_364_p2;
reg    ap_block_state1;
reg   [9:0] pixWindow_val_val_V_0_2_0_0_i_fu_68;
wire    ap_CS_fsm_state4;
reg   [9:0] pixWindow_val_val_V_0_2_1_0_i_fu_72;
reg   [9:0] pixWindow_val_val_V_0_2_2_0_i_fu_76;
reg   [9:0] pixWindow_val_val_V_1_1_0_0_i_fu_80;
reg   [9:0] pixWindow_val_val_V_1_1_1_0_i_fu_84;
reg   [9:0] pixWindow_val_val_V_1_1_2_0_i_fu_88;
reg   [9:0] pixWindow_val_val_V_1_2_0_0_i_fu_92;
reg   [9:0] pixWindow_val_val_V_1_2_1_0_i_fu_96;
reg   [9:0] pixWindow_val_val_V_1_2_2_0_i_fu_100;
reg   [9:0] pixWindow_val_val_V_2_2_0_0_i_fu_104;
reg   [9:0] pixWindow_val_val_V_2_2_1_0_i_fu_108;
reg   [9:0] pixWindow_val_val_V_2_2_2_0_i_fu_112;
reg   [9:0] pixBuf_val_V_0_0_0_i_fu_116;
reg   [9:0] pixBuf_val_V_0_1_0_i_fu_120;
reg   [9:0] pixBuf_val_V_0_2_0_i_fu_124;
reg   [9:0] pixBuf_val_V_1_0_0555_i_fu_128;
reg   [9:0] pixBuf_val_V_1_1_0556_i_fu_132;
reg   [9:0] pixBuf_val_V_1_2_0557_i_fu_136;
reg   [9:0] pixBuf_val_V_2_0_0558_i_fu_140;
reg   [9:0] pixBuf_val_V_2_1_0559_i_fu_144;
reg   [9:0] pixBuf_val_V_2_2_0560_i_fu_148;
wire   [11:0] zext_ln830_fu_355_p1;
wire   [0:0] empty_166_fu_454_p1;
wire   [0:0] out_y_cast_i_fu_465_p2;
wire   [14:0] and215_cast_i_fu_471_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_ap_start_reg = 1'b0;
end

system_v_demosaic_0_1_DebayerRandBatG_lineBuffer_val_V_0 #(
    .DataWidth( 30 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
lineBuffer_val_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_0_i_address0),
    .ce0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_0_i_ce0),
    .we0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_0_i_we0),
    .d0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_0_i_d0),
    .address1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_0_i_address1),
    .ce1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_0_i_ce1),
    .q1(lineBuffer_val_V_0_q1)
);

system_v_demosaic_0_1_DebayerRandBatG_lineBuffer_val_V_0 #(
    .DataWidth( 30 ),
    .AddressRange( 1921 ),
    .AddressWidth( 11 ))
lineBuffer_val_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_1_i_address0),
    .ce0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_1_i_ce0),
    .we0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_1_i_we0),
    .d0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_1_i_d0),
    .address1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_1_i_address1),
    .ce1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_1_i_ce1),
    .q1(lineBuffer_val_V_1_q1)
);

system_v_demosaic_0_1_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2 grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_ap_start),
    .ap_done(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_ap_done),
    .ap_idle(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_ap_idle),
    .ap_ready(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_ap_ready),
    .imgRB_dout(imgRB_dout),
    .imgRB_empty_n(imgRB_empty_n),
    .imgRB_read(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_imgRB_read),
    .imgRgb_din(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_imgRgb_din),
    .imgRgb_full_n(imgRgb_full_n),
    .imgRgb_write(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_imgRgb_write),
    .pixBuf_val_V_2_2_0560_i(pixBuf_val_V_2_2_0560_i_fu_148),
    .pixBuf_val_V_2_1_0559_i(pixBuf_val_V_2_1_0559_i_fu_144),
    .pixBuf_val_V_2_0_0558_i(pixBuf_val_V_2_0_0558_i_fu_140),
    .pixBuf_val_V_1_2_0557_i(pixBuf_val_V_1_2_0557_i_fu_136),
    .pixBuf_val_V_1_1_0556_i(pixBuf_val_V_1_1_0556_i_fu_132),
    .pixBuf_val_V_1_0_0555_i(pixBuf_val_V_1_0_0555_i_fu_128),
    .pixBuf_val_V_0_2_0_i(pixBuf_val_V_0_2_0_i_fu_124),
    .pixBuf_val_V_0_1_0_i(pixBuf_val_V_0_1_0_i_fu_120),
    .pixBuf_val_V_0_0_0_i(pixBuf_val_V_0_0_0_i_fu_116),
    .pixWindow_val_val_V_2_2_2_0_i(pixWindow_val_val_V_2_2_2_0_i_fu_112),
    .pixWindow_val_val_V_2_2_1_0_i(pixWindow_val_val_V_2_2_1_0_i_fu_108),
    .pixWindow_val_val_V_2_2_0_0_i(pixWindow_val_val_V_2_2_0_0_i_fu_104),
    .pixWindow_val_val_V_1_2_2_0_i(pixWindow_val_val_V_1_2_2_0_i_fu_100),
    .pixWindow_val_val_V_1_2_1_0_i(pixWindow_val_val_V_1_2_1_0_i_fu_96),
    .pixWindow_val_val_V_1_2_0_0_i(pixWindow_val_val_V_1_2_0_0_i_fu_92),
    .pixWindow_val_val_V_1_1_2_0_i(pixWindow_val_val_V_1_1_2_0_i_fu_88),
    .pixWindow_val_val_V_1_1_1_0_i(pixWindow_val_val_V_1_1_1_0_i_fu_84),
    .pixWindow_val_val_V_1_1_0_0_i(pixWindow_val_val_V_1_1_0_0_i_fu_80),
    .pixWindow_val_val_V_0_2_2_0_i(pixWindow_val_val_V_0_2_2_0_i_fu_76),
    .pixWindow_val_val_V_0_2_1_0_i(pixWindow_val_val_V_0_2_1_0_i_fu_72),
    .pixWindow_val_val_V_0_2_0_0_i(pixWindow_val_val_V_0_2_0_0_i_fu_68),
    .add_ln830_i(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_add_ln830_i),
    .x_phase_i(x_phase_reg_941),
    .xor_i(xor_i_reg_1027),
    .out_y_i(out_y_i_reg_1022),
    .width_cast(width),
    .lineBuffer_val_V_0_i_address0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_0_i_address0),
    .lineBuffer_val_V_0_i_ce0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_0_i_ce0),
    .lineBuffer_val_V_0_i_we0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_0_i_we0),
    .lineBuffer_val_V_0_i_d0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_0_i_d0),
    .lineBuffer_val_V_0_i_address1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_0_i_address1),
    .lineBuffer_val_V_0_i_ce1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_0_i_ce1),
    .lineBuffer_val_V_0_i_q1(lineBuffer_val_V_0_q1),
    .lineBuffer_val_V_1_i_address0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_1_i_address0),
    .lineBuffer_val_V_1_i_ce0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_1_i_ce0),
    .lineBuffer_val_V_1_i_we0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_1_i_we0),
    .lineBuffer_val_V_1_i_d0(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_1_i_d0),
    .lineBuffer_val_V_1_i_address1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_1_i_address1),
    .lineBuffer_val_V_1_i_ce1(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_lineBuffer_val_V_1_i_ce1),
    .lineBuffer_val_V_1_i_q1(lineBuffer_val_V_1_q1),
    .cmp37_i(cmp37_i_reg_1032),
    .cmp140_i(cmp140_i_reg_1037),
    .pixBuf_val_V_2_2_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_2_2_1_i_out),
    .pixBuf_val_V_2_2_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_2_2_1_i_out_ap_vld),
    .pixBuf_val_V_2_1_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_2_1_1_i_out),
    .pixBuf_val_V_2_1_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_2_1_1_i_out_ap_vld),
    .pixBuf_val_V_2_0_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_2_0_1_i_out),
    .pixBuf_val_V_2_0_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_2_0_1_i_out_ap_vld),
    .pixBuf_val_V_1_2_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_1_2_1_i_out),
    .pixBuf_val_V_1_2_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_1_2_1_i_out_ap_vld),
    .pixBuf_val_V_1_1_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_1_1_1_i_out),
    .pixBuf_val_V_1_1_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_1_1_1_i_out_ap_vld),
    .pixBuf_val_V_1_0_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_1_0_1_i_out),
    .pixBuf_val_V_1_0_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_1_0_1_i_out_ap_vld),
    .pixBuf_val_V_0_2_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_0_2_1_i_out),
    .pixBuf_val_V_0_2_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_0_2_1_i_out_ap_vld),
    .pixBuf_val_V_0_1_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_0_1_1_i_out),
    .pixBuf_val_V_0_1_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_0_1_1_i_out_ap_vld),
    .pixBuf_val_V_0_0_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_0_0_1_i_out),
    .pixBuf_val_V_0_0_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_0_0_1_i_out_ap_vld),
    .pixWindow_val_val_V_2_1_2_2_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_2_1_2_2_i_out),
    .pixWindow_val_val_V_2_1_2_2_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_2_1_2_2_i_out_ap_vld),
    .pixWindow_val_val_V_2_1_1_2_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_2_1_1_2_i_out),
    .pixWindow_val_val_V_2_1_1_2_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_2_1_1_2_i_out_ap_vld),
    .pixWindow_val_val_V_2_1_0_2_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_2_1_0_2_i_out),
    .pixWindow_val_val_V_2_1_0_2_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_2_1_0_2_i_out_ap_vld),
    .pixWindow_val_val_V_1_1_2_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_1_1_2_i_out),
    .pixWindow_val_val_V_1_1_2_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_1_1_2_i_out_ap_vld),
    .pixWindow_val_val_V_1_1_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_1_1_1_i_out),
    .pixWindow_val_val_V_1_1_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_1_1_1_i_out_ap_vld),
    .pixWindow_val_val_V_1_1_0_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_1_1_0_i_out),
    .pixWindow_val_val_V_1_1_0_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_1_1_0_i_out_ap_vld),
    .pixWindow_val_val_V_1_0_2_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_1_0_2_i_out),
    .pixWindow_val_val_V_1_0_2_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_1_0_2_i_out_ap_vld),
    .pixWindow_val_val_V_1_0_1_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_1_0_1_i_out),
    .pixWindow_val_val_V_1_0_1_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_1_0_1_i_out_ap_vld),
    .pixWindow_val_val_V_1_0_0_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_1_0_0_i_out),
    .pixWindow_val_val_V_1_0_0_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_1_0_0_i_out_ap_vld),
    .pixWindow_val_val_V_0_1_2_2_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_0_1_2_2_i_out),
    .pixWindow_val_val_V_0_1_2_2_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_0_1_2_2_i_out_ap_vld),
    .pixWindow_val_val_V_0_1_1_2_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_0_1_1_2_i_out),
    .pixWindow_val_val_V_0_1_1_2_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_0_1_1_2_i_out_ap_vld),
    .pixWindow_val_val_V_0_1_0_2_i_out(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_0_1_0_2_i_out),
    .pixWindow_val_val_V_0_1_0_2_i_out_ap_vld(grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_0_1_0_2_i_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln830_fu_359_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln830_fu_359_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_ap_start_reg <= 1'b1;
        end else if ((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_ap_ready == 1'b1)) begin
            grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (bayerPhase_c_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_64 <= 11'd0;
    end else if (((icmp_ln830_fu_359_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        y_fu_64 <= y_6_fu_364_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln830_fu_359_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        cmp140_i_reg_1037 <= cmp140_i_fu_487_p2;
        cmp37_i_reg_1032 <= cmp37_i_fu_481_p2;
        out_y_i_reg_1022 <= out_y_i_fu_458_p2;
        xor_i_reg_1027 <= xor_i_fu_475_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        pixBuf_val_V_0_0_0_i_fu_116 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_0_0_1_i_out;
        pixBuf_val_V_0_1_0_i_fu_120 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_0_1_1_i_out;
        pixBuf_val_V_0_2_0_i_fu_124 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_0_2_1_i_out;
        pixBuf_val_V_1_0_0555_i_fu_128 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_1_0_1_i_out;
        pixBuf_val_V_1_1_0556_i_fu_132 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_1_1_1_i_out;
        pixBuf_val_V_1_2_0557_i_fu_136 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_1_2_1_i_out;
        pixBuf_val_V_2_0_0558_i_fu_140 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_2_0_1_i_out;
        pixBuf_val_V_2_1_0559_i_fu_144 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_2_1_1_i_out;
        pixBuf_val_V_2_2_0560_i_fu_148 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixBuf_val_V_2_2_1_i_out;
        pixWindow_val_val_V_0_2_0_0_i_fu_68 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_0_1_0_2_i_out;
        pixWindow_val_val_V_0_2_1_0_i_fu_72 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_0_1_1_2_i_out;
        pixWindow_val_val_V_0_2_2_0_i_fu_76 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_0_1_2_2_i_out;
        pixWindow_val_val_V_1_1_0_0_i_fu_80 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_1_0_0_i_out;
        pixWindow_val_val_V_1_1_1_0_i_fu_84 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_1_0_1_i_out;
        pixWindow_val_val_V_1_1_2_0_i_fu_88 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_1_0_2_i_out;
        pixWindow_val_val_V_1_2_0_0_i_fu_92 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_1_1_0_i_out;
        pixWindow_val_val_V_1_2_1_0_i_fu_96 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_1_1_1_i_out;
        pixWindow_val_val_V_1_2_2_0_i_fu_100 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_1_1_2_i_out;
        pixWindow_val_val_V_2_2_0_0_i_fu_104 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_2_1_0_2_i_out;
        pixWindow_val_val_V_2_2_1_0_i_fu_108 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_2_1_1_2_i_out;
        pixWindow_val_val_V_2_2_2_0_i_fu_112 <= grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_pixWindow_val_val_V_2_1_2_2_i_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        trunc_ln822_1_i_reg_946 <= {{bayerPhase_c_dout[15:1]}};
        x_phase_reg_941 <= x_phase_fu_327_p1;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (bayerPhase_c_empty_n == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln830_fu_359_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln830_fu_359_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_c_blk_n = bayerPhase_c_empty_n;
    end else begin
        bayerPhase_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (bayerPhase_c_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        bayerPhase_c_read = 1'b1;
    end else begin
        bayerPhase_c_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        imgRB_read = grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_imgRB_read;
    end else begin
        imgRB_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        imgRgb_write = grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_imgRgb_write;
    end else begin
        imgRgb_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (bayerPhase_c_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln830_fu_359_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and215_cast_i_fu_471_p1 = out_y_cast_i_fu_465_p2;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (bayerPhase_c_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign cmp140_i_fu_487_p2 = ((y_fu_64 != 11'd0) ? 1'b1 : 1'b0);

assign cmp37_i_fu_481_p2 = ((y_fu_64 < height) ? 1'b1 : 1'b0);

assign empty_166_fu_454_p1 = y_fu_64[0:0];

assign grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_add_ln830_i = (width + 11'd1);

assign grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_ap_start = grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_ap_start_reg;

assign icmp_ln830_fu_359_p2 = ((y_fu_64 == loopHeight_fu_321_p2) ? 1'b1 : 1'b0);

assign imgRgb_din = grp_DebayerRandBatG_Pipeline_VITIS_LOOP_833_2_fu_262_imgRgb_din;

assign loopHeight_fu_321_p2 = (height + 11'd1);

assign out_y_cast_i_fu_465_p2 = (empty_166_fu_454_p1 ^ 1'd1);

assign out_y_i_fu_458_p2 = ($signed(zext_ln830_fu_355_p1) + $signed(12'd4095));

assign x_phase_fu_327_p1 = bayerPhase_c_dout[0:0];

assign xor_i_fu_475_p2 = (trunc_ln822_1_i_reg_946 ^ and215_cast_i_fu_471_p1);

assign y_6_fu_364_p2 = (y_fu_64 + 11'd1);

assign zext_ln830_fu_355_p1 = y_fu_64;

endmodule //system_v_demosaic_0_1_DebayerRandBatG
